### ISSUE TITLE
Error: Installing npm packages failed

### ISSUE THREAD

**Issue by samylov** [basys/basys#1]
D:\JS\PROJECTS\Vue\BasysTemp>npm i -g basys-cli && basys init
C:\Users\User001\AppData\Roaming\npm\basys -> C:\Users\User001\AppData\Roaming\npm\node_modules\basys-cli\index.js
+ basys-cli@0.3.1
added 166 packages in 10.232s
? Select a starter project Todo list sample web app
? Project location .
? Would you like to add Visual Studio Code settings? Yes
Error: Installing npm packages failed
    at initProject (C:\Users\User001\AppData\Roaming\npm\node_modules\basys-cli\utils.js:215:13)
    at <anonymous>

**Comment by sergkop** [comment]
Hm, it is what it says - `npm install` command failed. Could you run it explicitly and see what the problem is?
I may improve the error handling here and print the actual command output on failure.

**Comment by samylov** [comment]
Sorry, I dont understand what do you mean "run it explicitly".

**Comment by sergkop** [comment]
Hm, that seems to be a problem with node-sass library. Normally it shouldn't require python to be installed. I'll look into it tonight. Meanwhile, you can try installing python 2.

**Comment by sergkop** [comment]
So the problem you are having is related to the network, not node-sass itself. The script failed to download this binary https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-57_binding.node. Could be a temporary issue or a result of blocking the internet (in case you are in Russia).

The workaround is to do the following before running `npm install` again (from [node-gyp docs](https://github.com/nodejs/node-gyp#option-1)):
> Install all the required tools and configurations using Microsoft's windows-build-tools using `npm install --global --production windows-build-tools` from an elevated PowerShell or CMD.exe (run as Administrator).

**Comment by samylov** [comment]
Oh... With VPN work fine.
