### ISSUE TITLE
When generating blank project, there any many empty of missing files

### ISSUE THREAD

**Issue by lsbyerley** [basys/basys#4]
Was trying out basys, love the idea and concept. Just wanted to let you know I'm not seeing any webpack configs, src/backend.js, and src/web.js are blank when generating a blank starter project (did not choose visual studio code settings).

**Comment by sergkop** [comment]
Thanks!
Indeed, src/backend.js and src/web.js were confusingly empty - I've added some explanations inside https://github.com/basys/basys-starter-project/commit/d9caa930e4d59088e23508caf880624e2475e467.
As for webpack config - there isn't any. The idea is that it is hidden inside Basys (like in Nuxt) and you can configure bundling and many other things in [basys.json](https://basys.io/docs/configuration). However, I can see that it won't cover all use cases and I may add support for custom webpack config later.
